---
- name: Python environment & computing packages installation
  connection: ssh
  gather_facts: false
  hosts: all
  tasks:
    - name: Install a Python3 VENV and pip
      become: "yes"
      apt:
        name: "{{ packages }}"
        update_cache: "yes"
      vars:
        packages:
        - zip 
        - protobuf-compiler
        - libprotobuf-dev
        - openssl
        - libssl-dev
        - libcurl4-openssl-dev
        - python3-setuptools
        - python3-venv
        - python3-pip
        - python3-dev
        - gfortran
        - libatlas3-base
        - libatlas-base-dev
        - libopenblas-base
        - libopenblas-dev
        - musl
        - musl-dev
        - liblapack3
        - liblapack-dev
        - libblas3
        - libblas-dev
        - liblapack3
        - liblapack-dev
        - liblapacke
        - liblapacke-dev
        - libfreetype6
        - libfreetype6-dev
        - libffi6
        - libffi-dev
        - libpython3-dev
        - libhdf5-serial-dev 
        - hdf5-tools 
        - libhdf5-dev 
        - libssl-dev
        - zlib1g-dev 
        - libjpeg8-dev
        - llvm-7-dev
        - pybind11-dev
        # python3-scipy
        # python3-sklearn
        # python3-sklearn-pandas
    - name: Fix llvm-config path with symblic link
      file:
          src: "llvm-config-7"
          dest: "/usr/bin/llvm-config"
          state: link
    - name: Upgrade pip
      become: "yes"
      pip:
        name:
            - pip
            - testresources
            - setuptools
        extra_args: --upgrade
        executable: pip3
    - name: Upgrade wheel
      become: "yes"
      pip:
        name: wheel
        extra_args: --upgrade
        executable: pip3
    - name: Install NumPy and other packages
      become: "yes"
      pip:
        executable: pip3
        name:
            - cython
            - pybind11
            - pandas
            - matplotlib
            - tqdm
            - jupyter
            - jupyterthemes
            - numpy
            - future
            - mock
            - h5py
    - name: Install Keras, Scipy...
      become: "yes"
      pip:
        executable: pip3
        name:
            - keras_preprocessing
            - keras_applications
            - gast
            - futures
            - protobuf
            - grpcio
            - absl-py
            - py-cpuinfo
            - psutil
            - portpicker
            - six
            - requests
            - astor
            - termcolor
            - wrapt
            - google-pasta
            - librosa
            - sklearn
            - sklearn-pandas
    - name: Install TensorFlow
      become: "yes"
      pip:
        name: tensorflow-gpu
        extra_args: --pre --extra-index-url https://developer.download.nvidia.com/compute/redist/jp/v43
        executable: pip3
    - name: Jupyter Theme Settings
      command: jt -t monokai -f fira {{ item }}
      with_items: 
        - -fs 13 -nf ptsans -nfs 11 -N -kl -cursw 5 -cursc r -cellw 95% -T
        - -fs 11 -nf ptsans -nfs 11 -N -kl -cursw 5 -cursc r -cellw 95% -T -vim
